// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.Data;

#nullable disable

namespace Project.Migrations.AnotherDB
{
    [DbContext(typeof(AnotherDBContext))]
    partial class AnotherDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project.Models.Club", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("street")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID");

                    b.ToTable("Clubs");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            city = "Kraków",
                            name = "Crossfit Box",
                            street = "Długa 12"
                        },
                        new
                        {
                            ID = 2,
                            city = "Kraków",
                            name = "Hells gym",
                            street = "Krótka 65C"
                        },
                        new
                        {
                            ID = 3,
                            city = "Warszawa",
                            name = "Poland Mountain",
                            street = "Pokątna 12"
                        },
                        new
                        {
                            ID = 4,
                            city = "Sosnowiec",
                            name = "Rainbow Park",
                            street = "Sezamkowa 2137"
                        });
                });

            modelBuilder.Entity("Project.Models.Opinion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("clubID")
                        .HasColumnType("int");

                    b.Property<int>("rateNumber")
                        .HasColumnType("int");

                    b.Property<string>("text")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ID");

                    b.ToTable("Opinions");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            clubID = 1,
                            rateNumber = 5,
                            text = "The gym's extensive and modern equipment receives a top rating for providing a well-rounded fitness experience, suitable for all levels."
                        },
                        new
                        {
                            ID = 2,
                            clubID = 1,
                            rateNumber = 4,
                            text = "The energetic atmosphere and motivational decor contribute positively to the workout environment, though there is always room for enhancement."
                        },
                        new
                        {
                            ID = 3,
                            clubID = 2,
                            rateNumber = 5,
                            text = "The staff's friendliness and expertise in guiding members through workouts earn a high rating, ensuring a safe and effective exercise routine."
                        },
                        new
                        {
                            ID = 4,
                            clubID = 2,
                            rateNumber = 4,
                            text = "The gym's commitment to cleanliness is commendable, but there might be occasional improvements needed to maintain a consistently spotless environment."
                        },
                        new
                        {
                            ID = 5,
                            clubID = 3,
                            rateNumber = 5,
                            text = "Offering diverse fitness classes and programs for all interests and skill levels earns top marks for keeping workouts engaging and challenging."
                        },
                        new
                        {
                            ID = 6,
                            clubID = 3,
                            rateNumber = 5,
                            text = "The gym's extended hours receive high praise for accommodating a variety of schedules, ensuring members can conveniently fit in their workouts."
                        },
                        new
                        {
                            ID = 7,
                            clubID = 4,
                            rateNumber = 4,
                            text = "The gym's efforts to build a sense of community among members are appreciated, though there is some room for additional engagement and connection opportunities."
                        },
                        new
                        {
                            ID = 8,
                            clubID = 4,
                            rateNumber = 5,
                            text = "Considering the facilities, services, and overall experience, the gym offers excellent value for money, justifying the membership fees with its high-quality offerings."
                        });
                });

            modelBuilder.Entity("Project.Models.Pass", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("numberOfAvailableClubs")
                        .HasColumnType("int");

                    b.Property<int>("numberOfEntries")
                        .HasColumnType("int");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Passes");
                });
#pragma warning restore 612, 618
        }
    }
}
